
name: Build Offline Windows Installer

on:
  workflow_dispatch:
  push:
    paths:
      - 'installer/windows/**'
      - '.github/workflows/**'
      - '**.py'
      - 'requirements.txt'
      - 'anbar_pro/**'
      - 'inventory/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python (builder)
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create venv and install deps
        run: |
          python -m venv .venv
          .\.venv\Scripts\python -m pip install --upgrade pip
          .\.venv\Scripts\pip install -r requirements.txt

      - name: Prepare offline runtime (copy venv)
        shell: pwsh
        run: |
          $rt = "runtime\venv"
          if (Test-Path $rt) { Remove-Item -Recurse -Force $rt }
          New-Item -ItemType Directory -Path $rt | Out-Null
          robocopy ".venv\Scripts" "$rt\Scripts" /E | Out-Null
          robocopy ".venv\Lib" "$rt\Lib" /E | Out-Null
          if (Test-Path ".venv\DLLs") { robocopy ".venv\DLLs" "$rt\DLLs" /E | Out-Null }
          # quick sanity check
          & "$rt\Scripts\python.exe" -c "import sys; print(sys.version)"

      - name: Install Inno Setup via choco
        shell: pwsh
        run: |
          choco install innosetup --no-progress -y
          $env:Path += ";C:\Program Files (x86)\Inno Setup 6"

      - name: Build installer (ISCC)
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" ".\installer\windows\AnbarPro_Offline.iss"

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: AnbarPro-Setup-Offline
          path: |
            AnbarPro-Setup-Offline.exe
            installer/windows/*.iss
            runtime/**/*
