services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: anbar
      POSTGRES_USER: anbar
      POSTGRES_PASSWORD: anbar
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      POSTGRES_DB: anbar
      POSTGRES_USER: anbar
      POSTGRES_PASSWORD: anbar
      POSTGRES_HOST: db
      DJANGO_ALLOWED_HOSTS: "*"
      DJANGO_DEBUG: "1"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  pg:
